Navn	Beskrivelse	Status  	Starttype	Log på som
ActiveX-installationsprogram (AxInstSV)	Gør det muligt at validere Kontrol af brugerkonti for installationen af ActiveX-objekter fra internettet og gør det muligt at administrere installationen af ActiveX-objekter på baggrund af indstillingerne for gruppepolitik. Denne tjeneste starter efter behov, og hvis den deaktiveres, fungerer installationen af ActiveX-objekter i overensstemmelse med standardindstillingerne for browser.		Manuelt	Lokalt system
Adgang til brugerdata_42ad2	Giver apps adgang til strukturerede brugerdata, herunder kontaktoplysninger, kalendere, beskeder og andet indhold. Hvis du stopper eller deaktiverer tjenesten, vil de apps, der bruger disse data, muligvis ikke virke korrekt.		Manuelt	Lokalt system
Administration af downloadede kort	Windows-tjeneste, der giver programmer adgang til downloadede kort. Tjenesten startes efter behov af det program, der bruger de downloadede kort. Hvis du deaktiverer tjenesten, kan programmer ikke få adgang til kort.		Automatisk (forsinket start)	Netværkstjeneste
Administration af lagerniveauer	Optimerer placeringen af data i lagerniveauer på alle lagdelte lagerpladser i systemet.		Manuelt	Lokalt system
Agent Activation Runtime_42ad2	Runtime for activating conversational agent applications		Manuelt	Lokalt system
AllJoyn-routertjeneste	Dirigerer AllJoyn-meddelelser til de lokale AllJoyn-klienter. Hvis denne tjeneste stoppes, vil de AllJoyn-klienter, der ikke har deres egne medfølgende routere, ikke kunne køre.		Manuel (udløser start)	Lokal tjeneste
Anbefalet tjeneste til fejlfinding	Aktiverer automatisk afhjælpning af kendte problemer ved at anvende den anbefalede fejlfinding. Hvis den stoppes, får enheden ikke anbefalet fejlfinding af problemer på enheden.		Manuelt	Lokalt system
Anskaffelseshændelser for stillbillede	Starter programmer, der er knyttet til anskaffelseshændelser for stillbillede.		Manuelt	Lokalt system
App-parathed	Gør apps parat til brug, første gang en bruger logger på denne pc, og når nye apps tilføjes.		Manuelt	Lokalt system
AppX Deployment Service (AppXSVC)	Provides infrastructure support for deploying Store applications. This service is started on demand and if disabled Store applications will not be deployed to the system, and may not function properly.	Kører	Manuel (udløser start)	Lokalt system
Arbejdsstation	Opretter og vedligeholder klientnetværkstilslutninger til fjernservere ved hjælp af SMB-protokollen. Hvis denne tjeneste standses, er disse tilslutninger ikke tilgængelige. Hvis tjenesten deaktiveres, kan tjenester, der er udtrykkeligt afhængige af den, ikke startes.	Kører	Automatisk	Netværkstjeneste
Assistent til netværksforbindelser	Tildeler DirectAccess-statusmeddelelse til komponenter på brugergrænsefladen		Manuel (udløser start)	Lokalt system
Automatisk konfiguration af 802.3-netværk	Tjenesten Automatisk konfiguration af 802.3-netværk (DOT3SVC) skal udføre IEEE 802.1X-godkendelse på Ethernet-grænseflader. Hvis den aktuelle netværksinstallation gennemtvinger 802.1X-godkendelse, skal DOT3SVC-tjenesten konfigureres til at køre for at oprette en lag 2-forbindelse og/eller give adgang til netværksressourcer. Traditionelle netværk, der ikke gennemtvinger 802.1X-godkendelse, påvirkes ikke af DOT3SVC-tjenesten.		Manuelt	Lokalt system
Automatisk konfiguration af enheder med forbindelse til netværket	Tjenesten til automatisk konfiguration af enheder med netværksforbindelse overvåger og installerer kvalificerede enheder, der opretter forbindelse til et kvalificeret netværk. Hvis du stopper eller deaktiverer denne tjeneste, vil Windows ikke kunne registrere og installere kvalificerede enheder med netværksforbindelse automatisk. Brugerne kan stadig manuelt føje enheder med netværksforbindelse til en pc via brugergrænsefladen.		Manuel (udløser start)	Lokal tjeneste
Automatisk opdateringsfunktion til tidszoner	Nulstiller automatisk systemets tidszone.		Deaktiveret	Lokal tjeneste
AVCTP-tjeneste	Dette er AVCTP-tjenesten (Audio Video Control Transport Protocol)	Kører	Manuel (udløser start)	Lokal tjeneste
BFE (Base Filtering Engine)	Tjenesten BFE (Base Filtering Engine) er en tjeneste, der administrerer politikker for firewalls og IPsec (Internet Protocol security) og implementerer brugertilstandsfiltrering. Stop og deaktivering af tjenesten BFE vil reducere systemets sikkerhed væsentligt. Det vil også resultere i uforudsigelig adfærd i IPsec-administration og firewallprogrammer.	Kører	Automatisk	Lokal tjeneste
BITS (Background Intelligent Transfer Service)	Overfører filer i baggrunden ved hjælp af inaktiv netværksbåndbredde. Hvis tjenesten er deaktiveret, kan programmer, som er afhængige af BITS, f.eks. Windows Update eller MSN Explorer, ikke hente programmer og andre oplysninger automatisk.		Manuelt	Lokalt system
Bluetooth-lydgatewaytjeneste	Tjeneste, der understøtter lydgatewayrollen for den håndfri Bluetooth-profil.		Manuel (udløser start)	Lokal tjeneste
BranchCache	Denne tjeneste cachelagrer netværksindholdet fra peers på det lokale undernet.		Manuelt	Netværkstjeneste
Brave Update Tjeneste (brave)	Holder dit Brave-software opdateret. Hvis denne tjeneste deaktiveres eller stoppes, bliver dit Brave-software ikke opdateret, hvilket kan medføre, at sikkerhedsrisici ikke kan repareres, og at funktioner ikke kan fungere. Denne tjeneste afinstallerer sig selv, når den ikke bruges af noget Brave-software.		Automatisk (forsinket start)	Lokalt system
Brave Update Tjeneste (bravem)	Holder dit Brave-software opdateret. Hvis denne tjeneste deaktiveres eller stoppes, bliver dit Brave-software ikke opdateret, hvilket kan medføre, at sikkerhedsrisici ikke kan repareres, og at funktioner ikke kan fungere. Denne tjeneste afinstallerer sig selv, når den ikke bruges af noget Brave-software.		Manuelt	Lokalt system
Brugerstyring	Brugerstyring stiller de runtimekomponenter, der kræves til flerbrugerinteraktion, til rådighed. Hvis denne tjeneste stoppes, fungerer nogle programmer muligvis ikke korrekt.	Kører	Automatisk (udløser start)	Lokalt system
Brugertjeneste til platformen til tilsluttede enheder_42ad2	Denne brugertjeneste bruges i scenarier med platformen til tilsluttede enheder	Kører	Automatisk	Lokalt system
Brugertjeneste til udklipsholder_42ad2	Denne brugertjeneste bruges til scenarier med udklipsholderen	Kører	Manuelt	Lokalt system
BullGuard backup service	The BullGuard Backup service enables you to backup files that are in use		Manuelt	Lokalt system
BullGuard e-mail monitoring service	The BullGuard Email Monitoring service secures your e-mail client	Kører	Automatisk	Lokalt system
BullGuard firewall service	BullGuard Firewall protects you from hackers and unwanted network traffic	Kører	Automatisk	Lokalt system
BullGuard Helper Service	BullGuard Helper service is required for the proper system integration of your BullGuard security suite	Kører	Manuelt	Lokalt system
BullGuard Main Service	The BullGuard Main service is required for the proper functioning of your BullGuard security suite	Kører	Automatisk	Lokalt system
BullGuard on-access service	The BullGuard File Scan service performs on-access scan for detecting malware in real time	Kører	Automatisk	Lokalt system
BullGuard scanning service	The BullGuard Scan Service is the central anti-virus component of BullGuard Internet Security	Kører	Automatisk	Lokalt system
BullGuard Sentry Engine	The BullGuard Sentry service is an anti-virus component of BullGuard Internet Security	Kører	Automatisk	Lokalt system
BullGuard update service	The BullGuard Update service keeps your BullGuard security suite up-to-date, with the latest solutions against threats	Kører	Automatisk	Lokalt system
Capability Access Manager-tjeneste	Indeholder funktioner til administration af UWP-apps' adgang til appfunktioner samt til at kontrollere en apps adgang til bestemte appfunktioner	Kører	Manuelt	Lokalt system
CaptureService_42ad2	Aktiverer valgfri skærmoptagelsesfunktion til programmer, der kalder Windows.Graphics.Capture-API'en.		Manuelt	Lokalt system
Chipkort	Administrerer adgang til chipkort, der læses af denne computer. Hvis denne tjeneste stoppes, kan computeren ikke læse chipkort. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.		Manuel (udløser start)	Lokal tjeneste
CNG-nøgleisolering	Tjenesten CNG-nøgleisolering er hosted i LSA-processen. Tjenesten giver nøgleprocesisolering til private nøgler og tilknyttede kryptografiske handlinger i overensstemmelse med de fælles kriterier. Tjenesten lagrer og anvender langvarige nøgler i en sikker proces, der overholder de krav, der stilles i de fælles kriterier.	Kører	Manuel (udløser start)	Lokalt system
COM+ Event System	Understøtter SENS (System Event Notification Service), der indeholder automatisk distribution af hændelser til COM-komponenter, der benytter DTC. Hvis tjenesten stoppes, lukkes SENS, og tjenesten kan derfor ikke levere meddelelser om logon og logoff. Hvis tjenesten deaktiveres, kan tjenester, der direkte afhænger af den, ikke startes.	Kører	Automatisk	Lokal tjeneste
COM+-systemprogram	Styrer konfiguration og sporing af COM+-baserede (Component Object Model) komponenter. Hvis tjenesten stoppes, fungerer de fleste COM+-baserede tjenester ikke korrekt. Hvis tjenesten deaktiveres, kan tjenester, der direkte afhænger af den, ikke startes.		Manuelt	Lokalt system
ConsentUX_42ad2	Tillader, at ConnectUX og pc-indstillinger kan tilsluttes og parre sig med WiFi-skærme og Bluetooth-enheder.		Manuelt	Lokalt system
CoreMessaging	Manages communication between system components.	Kører	Automatisk	Lokal tjeneste
CredentialEnrollmentManagerUserSvc_42ad2	Styring af legitimationsoplysninger for tilmelding		Manuelt	Lokalt system
Dataforbrug	Dataforbrug i netværk, datagrænse, begrænse baggrundsdata, forbrugsbaseret netværk, netværk efter forbrug.	Kører	Automatisk	Lokal tjeneste
DeviceAssociationBroker_42ad2	Enables apps to pair devices		Manuelt	Lokalt system
DevicePicker_42ad2	Denne brugertjeneste bruges til at styre grænsefladen i Miracast, DLNA og DIAL		Manuelt	Lokalt system
DevicesFlow_42ad2	Tillader, at ConnectUX og pc-indstillinger kan tilsluttes og parre sig med Wi.Fi-skærme og Bluetooth-enheder.		Manuelt	Lokalt system
DevQuery Discovery-mægler til baggrundsopgaver	Gør det muligt for apps at finde enheder med en baggrundsopgave		Manuel (udløser start)	Lokalt system
DHCP-klientprogram	Registrerer og opdaterer IP-adresser og DNS-poster for denne computer. Hvis denne tjeneste stoppes, modtager denne computer ikke dynamiske IP-adresser og DNS-opdateringer. Hvis denne tjeneste deaktiveres, kan de tjenester, der er direkte afhængige af den, ikke starte.	Kører	Automatisk	Lokal tjeneste
Diagnostic Execution Service	Executes diagnostic actions for troubleshooting support		Manuel (udløser start)	Lokalt system
Diagnosticeringspolitik-tjeneste	Tjenesten Diagnosticeringspolitik gør det muligt at registrere problemer i, foretage fejlfinding af og implementere løsninger for Windows-komponenter. Hvis denne tjeneste stoppes, fungerer diagnosticeringen ikke længere.	Kører	Automatisk	Lokal tjeneste
Diagnosticeringssystemvært	Værten for diagnosticeringssystemet bruges af  tjenesten Diagnosticeringspolitik som vært for diagnosticeringsprogrammerne, der skal køre som et lokalt system. Hvis tjenesten stoppes, er der ingen af de diagnosticeringsprogrammer, som er afhængige af den, der fungerer længere.		Manuelt	Lokalt system
Diagnosticeringstjenestevært	Værten for diagnosticeringssystemet bruges af  tjenesten Diagnosticeringspolitik som vært for diagnosticeringsprogrammerne, der skal køre som en lokal tjeneste. Hvis tjenesten stoppes, er der ingen af de diagnosticeringsprogrammer, som er afhængige af den, der fungerer længere.	Kører	Manuelt	Lokal tjeneste
Distributed Link Tracking Client	Vedligeholder links mellem NTFS-filer i en computer og på tværs af computere på et netværk.	Kører	Automatisk	Lokalt system
DLL-host for ydelsestæller	Gør eksterne brugere og 64-bit-processer i stand til at forespørge på ydelsestællere, der levers af 32-bit DLL-filer. Hvis denne tjeneste stoppes, er det kun 32-bit-processer, der kan forespørge på ydelsestællere, der leveres af 32-bit DLL-filer.		Manuelt	Lokal tjeneste
DNS-klient	Ved hjælp af tjenesten DNS Client (dnscache) cachelagres DNS-navne (Domain Name System), og det fulde computernavn for denne computer registreres. Hvis tjenesten stoppes, oversættes DNS-navne fortsat. Resultaterne af forespørgsler om DNS-navne cachelagres imidlertid ikke, og computerens navn registreres ikke. Hvis tjenesten deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.	Kører	Automatisk (udløser start)	Netværkstjeneste
DTC (Distributed Transaction Coordinator)	Koordinerer transaktioner, der spænder over flere ressourcestyringsprogrammer, f.eks. databaser, meddelelseskøer og filsystemer. Hvis tjenesten stoppes, fuldføres transaktionerne ikke. Hvis tjenesten deaktiveres, kan tjenester, der direkte afhænger af den, ikke startes.		Manuelt	Netværkstjeneste
EAP (Extensible Authentication Protocol)	Tjenesten EAP (Extensible Authentication Protocol) yder netværksgodkendelse i scenarier, som f.eks. 802.1x traditionelt og trådløst netværk, VPN og NAP (Network Access Protection). EAP yder også programmeringsgrænseflader (API'er), der anvendes af netværksadgangsklienter, herunder trådløse klienter og VPN-klienter, under godkendelsesprocessen. Hvis du deaktiverer denne tjeneste, kan computeren ikke få adgang til netværk, der kræver EAP-godkendelse.		Manuelt	Lokalt system
EFS (Encrypting File System)	Leverer den kerneteknologi til filkryptering, der bruges til at lagre krypterede filer på enheder med NTFS-filsystemet. Hvis denne tjeneste stoppes eller deaktiveres, kan programmerne ikke få adgang til krypterede filer.		Manuel (udløser start)	Lokalt system
Enhedsinstallationstjeneste	Aktiverer en computer, så den genkender hardwareændringer og tilpasser sig disse med lidt eller intet input fra brugeren. Hvis denne tjeneste stoppes eller deaktiveres, resulterer det i at systemet bliver ustabilt.		Manuel (udløser start)	Lokalt system
Fjernskrivebord-tjenester	Tillader brugere at oprette interaktiv forbindelse til en fjerncomputer. Fjernskrivebord og værtsserveren for sessionen til Fjernskrivebord er afhængige af denne tjeneste. Du kan forhindre fjernbrug af denne computer ved at fjerne markeringerne i afkrydsningsfelterne under fanen Fjernforbindelse under System i Kontrolpanel.		Manuelt	Netværkstjeneste
Forbindelsesmægler for netværk	Mæglerforbindelser, der gør det muligt for Windows Store-apps at modtage meddelelser fra internettet.	Kører	Manuel (udløser start)	Lokalt system
Forældrekontrol	Gennemtvinger Forældrekontrol til underordnede konti i Windows. Hvis denne tjeneste stoppes eller deaktiveres, kan Forældrekontrol ikke gennemtvinges.		Deaktiveret	Lokalt system
GameDVR og udsend brugertjeneste_42ad2	Denne brugertjeneste bruges til spiloptagelser og live udsendelser		Manuelt	Lokalt system
Gatewaytjeneste til programlaget	Understøtter tredjeparts protokol-plug-ins for Deling af Internetforbindelse		Manuelt	Lokal tjeneste
Geoplaceringstjeneste	Denne tjeneste overvåger systemets aktuelle placering og administrerer geohegn (en geografisk placering med tilknyttede begivenheder). Hvis du slår tjenesten fra, vil programmer ikke kunne bruge eller modtage meddelelser til geoplacering eller geohegn.	Kører	Manuel (udløser start)	Lokalt system
GraphicsPerfSvc	Graphics performance monitor service		Manuel (udløser start)	Lokalt system
Gruppering af peer-netværk	Aktiverer kommunikation mellem flere parter ved hjælp af peer-to-peer-gruppering. Hvis indstillingen er deaktiveret, fungerer visse programmer, f.eks. Hjemmegruppe, måske ikke korrekt.		Manuelt	Lokal tjeneste
Hardwaregenkendelse på brugergrænsefladen	Indeholder beskeder om hardwarehændelser i forbindelse med automatisk afspilning.	Kører	Automatisk	Lokalt system
Hyper-V PowerShell Direct Service	Indeholder en funktion til administration af virtuel maskine med PowerShell via VM-session uden et virtuelt netværk.		Deaktiveret	Lokalt system
Hyper-V-funktion til øjebliksbillede af diskenhed	Koordinerer den kommunikation, der kræves for at bruge tjenesten Øjebliksbillede af diskenhed til at sikkerhedskopiere programmer og data på den virtuelle maskine fra operativsystemet på den fysiske computer.		Deaktiveret	Lokalt system
Hyper-V-grænseflade til gæstetjeneste	Grænseflade, som Hyper-V bruger til at interagere med bestemte tjeneste i den virtuelle maskine.		Deaktiveret	Lokalt system
Hyper-V-tjeneste til lukning af gæst	Indeholder en funktion til lukning af operativsystemet på den virtuelle maskine fra administrationsgrænseflade på den fysiske computer.		Deaktiveret	Lokalt system
Hyper-V-tjeneste til synkronisering af klokkeslæt	Synkroniserer systemet klokkeslæt på den virtuelle maskine med systemets klokkeslæt på den fysiske computer.		Deaktiveret	Lokal tjeneste
Hyper-V-tjeneste til udveksling af data	Indeholder en funktion til udveksling af data mellem den virtuelle maskine og det operativsystem, der kører på den fysiske computer.		Deaktiveret	Lokalt system
Hyper-V-tjeneste til virtualisering af fjernskrivebord	Indeholder en platform til kommunikation mellem den virtuelle maskine og operativsystemet på den fysiske computer.		Deaktiveret	Lokalt system
ICS (Internet Connection Sharing)	Giver mulighed for adresseoversættelse, adressering, navnefortolkning og/eller tjenester til forebyggelse af uautoriseret brug for netværksadresser på et hjemmenetværk eller mindre kontornetværk.		Manuel (udløser start)	Lokalt system
Identitetsstyring for peer-netværk	Tilbyder identitetstjenester til PNRP (Peer Name Resolution Protocol) og tjenester til peer-to-peer-gruppering. Hvis indstillingen deaktiveres, fungerer PNRP (Peer Name Resolution Protocol) og tjenesterne til peer-to-peer-gruppering måske ikke, og visse programmer, f.eks. Hjemmegruppe og Fjernsupport, fungerer måske ikke korrekt.		Manuelt	Lokal tjeneste
IKE- og AuthIP IPsec-nøglemoduler	Tjenesten IKEEXT er vært for nøglemodulerne IKE (Internet Key Exchange) og AuthIP (Authenticated Internet Protocol). Disse nøglemoduler anvendes til godkendelse og nøgleudvekslinger i IPsec (Internet Protocol security). Stop eller deaktivering af tjenesten IKEEXT deaktiverer IKE- og AuthIP-nøgleudveksling med peer-computere. IPsec konfigureres typisk til at bruge IKE eller AuthIP. Hvis du derfor stopper eller deaktiverer tjenesten IKEEXT, kan der opstå en IPsdc-fejl, som kan påvirke systemsikkerheden negativt. Det anbefales kraftigt, at du har tjenesten IKEEXT kørende.	Kører	Automatisk (udløser start)	Lokalt system
Infrastrukturtjeneste for baggrundsopgaver	Windows-infrastrukturtjeneste, der bestemmer, hvilke baggrundsopgaver der må køre på systemet.	Kører	Automatisk	Lokalt system
Installationsprogram til Windows-moduler	Muliggør installation, tilpasning og fjernelse af Windows-opdatering og valgfrie komponenter. Hvis tjenesten er deaktiveret, vil installation eller fjernelse af Windows-opdateringer muligvis mislykkes på denne computer.		Manuelt	Lokalt system
Integreret tilstand	Tjenesten Integreret tilstand aktiverer scenarier, der har relation til Baggrundsprogrammer. Hvis du deaktiverer tjenesten, kan Baggrundsprogrammer ikke aktiveres.		Manuel (udløser start)	Lokalt system
Intel(R) Content Protection HECI Service	Intel(R) Content Protection HECI Service - enables communication with the Content Protection FW		Manuelt	Lokalt system
Intel(R) HD Graphics Control Panel Service	Service for Intel(R) HD Graphics Control Panel	Kører	Automatisk	Lokalt system
IP-hjælpefunktioner	Giver tunnelforbindelser ved hjælp af IPv6-overgangsteknologier (6to4, ISATAP, Port Proxy og Teredo) og IP-HTTPS. Hvis denne tjeneste standses, kan de udvidede forbindelsesmuligheder, som disse teknologier medfører, ikke benyttes på computeren.	Kører	Automatisk	Lokalt system
IPsec Policy Agent	IPsec (Internet Protocol security) understøtter peer-godkendelse på netværksniveau, dataoprindelsesgodkendelse, dataintegritet, datafortrolighed (kryptering) og genafspilningsbeskyttelse. Denne tjeneste håndhæver IPsec-politikker, der er oprettet gennem snap-in'en IP Security Policies eller kommandolinjeværktøjet "netsh ipsec". Hvis du stopper denne tjeneste, kan du opleve problemer med netværkskommunikationen, hvis din politik kræver, at forbindelser bruger IPsec.  Fjernadministration af Windows Defender Firewall er desuden ikke tilgængelig, når denne tjeneste stoppes.	Kører	Manuel (udløser start)	Netværkstjeneste
Klient til gruppepolitik	Tjenesten bruges til at anvende de indstillinger, der er konfigureret af administratorer, for computeren og dens brugere via komponenten Gruppepolitik. Hvis tjenesten deaktiveres, anvendes indstillingerne ikke, og programmer og komponenter kan ikke administreres via Gruppepolitik. Alle komponenter eller programmer, som afhænger af komponenten Gruppepolitik, fungerer muligvis ikke, hvis tjenesten deaktiveres.	Kører	Automatisk (udløser start)	Lokalt system
Klientlicenstjeneste (ClipSVC)	Sikrer understøttelse af infrastrukturen til Microsoft Store. Denne tjeneste startes efter behov, og hvis deaktiverede programmer, der er købt i Windows Store, ikke fungerer korrekt.		Manuel (udløser start)	Lokalt system
Konfiguration af Fjernskrivebord	Tjenesten Konfiguration af Fjernskrivebord er ansvarlig for alle aktiviteter vedrørende konfiguration og sessionshåndtering af Fjernskrivebord-tjenester og Fjernskrivebord, som kræver systemkontekst. Disse omfatter midlertidige mapper under individuelle sessioner samt temaer og certifikater til Fjernskrivebord.		Manuelt	Lokalt system
Konfigurationstjeneste til IP-konvertering	Konfigurerer og giver mulighed for konvertering fra v4 til v6 og omvendt		Manuel (udløser start)	Lokalt system
Kontaktdata_42ad2	Indekserer kontaktdata for at give hurtigere indholdssøgning. Hvis du stopper eller deaktiverer tjenesten, kan der mangle kontakter i dine søgeresultater.		Manuelt	Lokalt system
Kryptografiske tjenester	Indeholder tre administrationstjenester: Tjenesten Katalogdatabase, der bekræfter signaturer for Windows-filer og tillader nye programmer at blive installeret, tjenesten Beskyttet rod, der tilføjer og fjerner certifikater på computeren fra rodnøglecentre, der er tillid til, og tjenesten Automatisk opdatering af rodcertifikat, som henter certifikater fra Windows Update og aktiverer scenarier som SSL. Hvis denne tjeneste stoppes, fungerer disse administrative tjenester ikke korrekt. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.	Kører	Automatisk	Netværkstjeneste
KtmRm til Distributed Transaction Coordinator	Koordinerer transaktioner mellem MSDTC (Distributed Transaction Coordinator) og KTM (Kernel Transaction Manager). Hvis det ikke er nødvendigt, anbefales det, at tjenesten forbliver stoppet. Hvis det er nødvendigt, startes tjenesten automatisk af både MSDTC og KTM. Hvis tjenesten er deaktiveret, vil alle de MSDTC-transaktioner, der interagerer med en Kernel Resource Manager medføre fejl, og alle de tjenester, der eksplicit afhænger af den, bliver ikke startet.		Manuel (udløser start)	Netværkstjeneste
Lagertjeneste	Leverer aktiveringstjenester til lagerindstillinger og udvidelse af eksternt lager	Kører	Automatisk (forsinket start, udløser start)	Lokalt system
Lagring af brugerdata_42ad2	Håndterer lagring af strukturerede brugerdata, herunder kontaktoplysninger, kalendere, beskeder og andet indhold. Hvis du stopper eller deaktiverer tjenesten, vil de apps, der bruger disse data, muligvis ikke virke korrekt.		Manuelt	Lokalt system
Leveringsoptimering	Udfører opgaver til optimering af indholdslevering		Automatisk (forsinket start, udløser start)	Netværkstjeneste
Lokal sessionsstyring	Kernetjeneste i Windows, der administrerer lokale brugersessioner. Hvis denne tjeneste stoppes eller deaktiveres, bliver systemet ustabilt.	Kører	Automatisk	Lokalt system
Meddelelsestjeneste_42ad2	Tjenesten understøtter sms'er og relaterede funktioner.		Manuel (udløser start)	Lokalt system
Microsoft (R) Diagnostics Hub Standard Collector Service	Diagnostics Hub Standard Collector Service. Når denne tjeneste kører, indsamler den realtids-ETW-hændelser og behandler dem.		Manuelt	Lokalt system
Microsoft App-V Client	Manages App-V users and virtual applications		Deaktiveret	Lokalt system
Microsoft Edge Elevation Service (MicrosoftEdgeElevationService)	Keeps Microsoft Edge up to update. If this service is disabled, the application will not be kept up to date.		Manuelt	Lokalt system
Microsoft Edge-opdatering-tjeneste (edgeupdate)	Holder din Microsoft-software opdateret. Hvis denne tjeneste deaktiveres eller stoppes, kan din Microsoft-software ikke holdes opdateret. Der kan opstå sikkerhedsproblemer, som ikke kan løses, og der kan være funktioner, som ikke virker. Tjenesten fjerner sig selv, når der ikke er Microsoft-software, som bruger den.		Deaktiveret	Lokalt system
Microsoft Edge-opdatering-tjeneste (edgeupdatem)	Holder din Microsoft-software opdateret. Hvis denne tjeneste deaktiveres eller stoppes, kan din Microsoft-software ikke holdes opdateret. Der kan opstå sikkerhedsproblemer, som ikke kan løses, og der kan være funktioner, som ikke virker. Tjenesten fjerner sig selv, når der ikke er Microsoft-software, som bruger den.		Deaktiveret	Lokalt system
Microsoft iSCSI-initiatortjeneste	Håndterer iSCSI-sessioner (Internet SCSI) fra denne computer til eksterne iSCSI-destinationsenheder. Hvis denne tjeneste er stoppet, vil denne computer ikke kunne logge på eller få adgang til iSCSI-destinationer. Hvis denne tjeneste er deaktiveret, vil eventuelle tjenester, der direkte afhænger af den, ikke kunne starte.		Manuelt	Lokalt system
Microsoft Lagerplads-SMP	Værtstjeneste til udbyderen af Microsoft Lagerpladsstyring. Hvis denne tjeneste er stoppet eller deaktiveret, kan Lagerpladser ikke administreres.		Manuelt	Netværkstjeneste
Microsoft Passport	Sikrer procesisolering for kryptografiske nøgler, der bruges til at godkende en brugers tilknyttede identitetsprovidere. Hvis denne tjeneste er deaktiveret, vil alle brugere og administrationen af disse nøgler ikke være tilgængelige, og det omfatter logon og enkeltlogon for apps og websteder. Denne tjeneste starter og stopper automatisk. Vi anbefaler, at du ikke konfigurerer denne tjeneste igen.		Manuel (udløser start)	Lokalt system
Microsoft Passport-beholder	Administrerer id-nøgler for lokale brugere, der anvendes til at godkende brugeren hos id-udbydere samt virtuelle TPM-chipkort. Hvis denne tjeneste deaktiveres, vil der ikke være adgang til id-nøgler for lokale brugere og virtuelle TPM-chipkort. Det anbefales, at du ikke ændrer konfigurationen af tjenesten.		Manuel (udløser start)	Lokal tjeneste
Microsoft Software-øjebliksbilledprovider	Administrerer softwarebaserede øjebliksbilleder, der tages af tjenesten Volume Shadow Copy. Hvis denne tjeneste stoppes, kan softwarebaserede øjebliksbilleder ikke administreres. Hvis denne tjeneste deaktiveres, kan ingen tjenester, der er direkte afhængige af den, starte.		Manuelt	Lokalt system
Microsoft Store-installationstjeneste	Giver infrastrukturunderstøttelse til Microsoft Store. Denne tjeneste startes efter behov, og hvis den er deaktiveret, vil installationerne ikke fungere korrekt.		Manuelt	Lokalt system
Microsoft-konto Logonassistent	Gør det muligt for brugere at logge på via id-tjenester til Microsoft-konti. Hvis tjenesten er stoppet, kan brugerne ikke logge på computeren med deres Microsoft-konto.	Kører	Manuel (udløser start)	Lokalt system
Mobilhotspot-tjeneste til Windows	Giver mulighed for at dele en mobildataforbindelse med en anden enhed.		Manuel (udløser start)	Lokal tjeneste
Mobiltid	Denne tjeneste indstiller klokkeslættet baseret på NITZ-meddelelser fra et mobilt netværk		Deaktiveret	Lokal tjeneste
Naturlig godkendelse	Signalsamletjeneste, der evaluerer signaler baseret på tid, netværk, geolokalisering, Bluetooth og CDF-faktorer. Understøttede faktorer er Lås enhed op, Dynamisk lås og Dynamo MDM-politikker		Manuel (udløser start)	Lokalt system
Net.Tcp-portdelingstjeneste	Angiver muligheden for at dele TCP-porte via protokollen net.tcp.		Deaktiveret	Lokal tjeneste
Netlogon	Opretholder en sikker kanal mellem denne computer og domænecontrolleren til godkendelse af brugere og tjenester. Hvis denne tjeneste er stoppet, kan computeren muligvis ikke godkende brugere og tjenester, og domænecontrolleren kan ikke registrere DNS-poster. Hvis denne tjeneste ikke er aktiveret, vil alle tjenester, der udtrykkeligt afhænger af den, ikke startes.		Manuelt	Lokalt system
Netværksforbindelser	Administrerer objekter i mappen Netværks- og opkaldsforbindelser, hvor du kan se forbindelser til både fjern- og lokalnetværk.		Manuelt	Lokalt system
NLA (Network Location Awareness)	Indsamler og gemmer konfigurationsoplysninger om netværket og giver programmer besked, når disse oplysninger ændres. Hvis tjenesten stoppes, er konfigurationsoplysningerne muligvis ikke tilgængelige. Hvis denne tjeneste deaktiveres, kan alle de tjenester, der direkte afhænger af den, ikke startes.	Kører	Automatisk	Netværkstjeneste
Offlinefiler	Tjenesten Offlinefiler udfører vedligeholdelse af cachen til Offlinefiler, besvarer brugerlogon- og -logoffhændelser, implementerer intern kode fra den offentlige API og sender interessante hændelser til dem, der er interesseret i offlinefilaktiviteter og ændringer i cachetilstanden.		Deaktiveret	Lokalt system
Opdagelsesmapper til link-layer-topologi	Opretter en netværkstilknytning, der består af oplysninger om computer- og enhedstopologi (forbindelse) samt metadata, der beskriver hver computer og enhed. Hvis denne tjeneste er deaktiveret, vil netværkstilknytningen ikke fungere korrekt.		Manuelt	Lokal tjeneste
Opdater Orchestrator-tjeneste	Administrerer Windows Update-opdateringer. Hvis den stoppes, kan dine enheder ikke downloade og installere de nyeste opdateringer.	Kører	Automatisk (forsinket start)	Lokalt system
Opgavestyring	Gør det muligt for brugeren at konfigurere og planlægge automatiserede opgaver på computeren. Tjenesten fungerer også som vært for flere vigtige systemopgaver i Windows. Hvis tjenesten er stoppet eller deaktiveret, bliver disse opgaver ikke kørt på de planlagte tidspunkter. Hvis tjenesten er deaktiveret, kan de tjenester, der er direkte afhængige af tjenesten, ikke startes.	Kører	Automatisk	Lokalt system
Optimer drev	Får computeren til at køre mere effektivt ved at optimere filer på lagerdrev.		Manuelt	Lokalt system
Optællingstjeneste for bærbar enhed	Gennemtvinger gruppepolitik for flytbare lagerenheder. Giver programmer, f.eks. Windows Media Player og guiden til import af billeder, mulighed for at overføre og synkronisere indhold ved hjælp af flytbare lagerenheder.		Manuel (udløser start)	Lokalt system
Overførsel af certifikat	Kopierer brugercertifikater og rodcertifikater fra chipkort til den aktuelle brugers certifikatlager, registrerer, hvornår der indsættes et chipkort i en chipkortlæser, og installerer eventuelt Plug and Play-minidriveren for chipkortet.		Manuel (udløser start)	Lokalt system
Platformstjeneste til tilsluttede enheder	Denne tjeneste bruges i scenarier med platformen til tilsluttede enheder	Kører	Automatisk (forsinket start, udløser start)	Lokal tjeneste
Plug and Play	Aktiverer en computer, så den genkender hardwareændringer og tilpasser sig disse med lidt eller intet input fra brugeren. Hvis denne tjeneste stoppes eller deaktiveres, resulterer det i at systemet bliver ustabilt.	Kører	Manuelt	Lokalt system
PNRP – Tjeneste til udgivelse af computernavn	Denne tjeneste udgiver et computernavn ved hjælp af PNRP (Peer Name Resolution Protocol). Konfigurationen styres via netsh-konteksten 'p2p pnrp peer' 		Manuelt	Lokal tjeneste
PNRP (Peer Name Resolution Protocol)	Aktiverer serveruafhængig peernavnefortolkning over internettet ved hjælp af PNRP (Peer Name Resolution Protocol). Hvis indstillingen deaktiveres, fungerer visse peer-to-peer- og samarbejdsprogrammer, f.eks. Fjernsupport, måske ikke korrekt.		Manuelt	Lokal tjeneste
Politik for fjernelse af chipkort	Gør det muligt at konfigurere systemet til at låse brugerens skrivebord, når chipkortet fjernes.		Manuelt	Lokalt system
Portomdirigering til Fjernskrivebord-tjenester i brugertilstand	Tillader omdirigering af printere/drev/porte til RDP-forbindelser		Manuelt	Lokalt system
Print Spooler	Denne tjeneste spooler udskriftsjob og håndterer interaktionen med printeren. Hvis du deaktiverer denne tjeneste, kan du hverken udskrive eller se dine printere.		Deaktiveret	Lokalt system
Printerudvidelser og -beskeder	Denne tjeneste åbner tilpassede printerdialogbokse og håndterer beskeder fra en ekstern printserver eller en printer. Hvis du deaktiverer denne tjeneste, kan du ikke se printerudvidelser og printerbeskeder.		Manuelt	Lokalt system
PrintWorkflow_42ad2	Understøtter programmer til arbejdsprocesser for udskrivning. Hvis du slår denne tjeneste fra, kan du muligvis ikke udskrive korrekt.		Manuelt	Lokalt system
Programadministration	Behandler anmodninger om installation, fjernelse og optælling af software, der er installeret via gruppepolitik. Hvis tjenesten er deaktiveret, kan brugerne ikke installere, fjerne eller optælle software, der er installeret via gruppepolitik. Hvis denne tjeneste er deaktiveret, er det ikke muligt at starte de tjenester, der afhænger direkte af tjenesten.		Manuelt	Lokalt system
Program-id	Bestemmer og bekræfter et programs identitet. Hvis denne tjeneste deaktiveres, kan AppLocker ikke gennemtvinges.		Manuel (udløser start)	Lokal tjeneste
Programkompatibilitetsassistent	Denne tjeneste indeholder understøttelse af PCA (Program Compatibility Assistant). PCA overvåger programmer, der installeres og køres af brugeren, og registrerer kendte kompatibilitetsproblemer. Hvis denne tjeneste standses, fungerer PCA ikke korrekt.	Kører	Manuelt	Lokalt system
Programoplysninger	Gør det lettere at køre interaktive programmer med yderligere administratorrettigheder. Hvis tjenesten afbrydes, kan brugerne ikke starte programmer med de yderligere administratorrettigheder, som de muligvis skal bruge til at udføre de ønskede brugeropgaver.	Kører	Manuel (udløser start)	Lokalt system
Punktbekræftelse	Kontrollerer mulige beskadigelser af filsystemet.		Manuel (udløser start)	Lokalt system
Quality Windows Audio Video Experience	Quality Windows Audio Video Experience (qWave) er en netværksplatform til programmer til AV-streaming (Audio Video) på private IP-netværk. qWave forbedrer ydeevnen og stabiliteten for AV-streaming ved at sikre netværkstjenestekvalitet (QoS) for AV-programmer. Det indeholder funktioner til adgangskontrol, overvågning og håndhævelse af kørselstid, feedback om programmet og trafikprioritering.		Manuelt	Lokal tjeneste
Radiostyringstjeneste	Radiostyrings- og flytilstandstjeneste	Kører	Manuelt	Lokal tjeneste
Remote Access Auto Connection Manager	Opretter en forbindelse til et fjernnetværk, når et program henviser til andre DNS- eller NetBIOS-navne eller adresser.		Manuelt	Lokalt system
Remote Access Connection Manager	Styrer opkalds- og VPN-forbindelser fra denne computer til internettet eller andre eksterne netværk. Hvis denne tjeneste deaktiveres, kan alle tjenester, der direkte afhænger af den, ikke starte.		Manuelt	Lokalt system
Remote Registry	Gør det muligt for fjernbrugere at ændre indstillingerne i registreringsdatabasen på denne computer. Hvis denne tjeneste stoppes, kan registreringsdatabasen kun ændres af brugere på denne computer. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.		Deaktiveret	Lokal tjeneste
Routing og Remote Access	Tilbyder routingtjenester til virksomheder i LAN- og WAN-miljøer.		Deaktiveret	Lokalt system
RPC (Remote Procedure Call )	Tjenesten RPCSS er tjenestekontrolstyringen for COM- og DCOM-servere. Det udfører anmodninger om objektaktivering, objekteksport og distribueret spildopsamling for COM- og DCOM-servere. Hvis tjenesten er stoppet eller deaktiveret, virker de programmer, der bruger COM eller DCOM, ikke korrekt. Det anbefales på det kraftigste, at tjenesten RPCSS kører.	Kører	Automatisk	Netværkstjeneste
RPC-slutpunktsafbildning	Fortolker RPC-grænseflade-id'er til transportslutpunkter. Hvis tjenesten stoppes eller deaktiveres, vil de programmer, der bruger tjenesten RPC (Remote Procedure Call), ikke virke korrekt.	Kører	Automatisk	Netværkstjeneste
RPS-søger (Remote Procedure Call)	I Windows 2003 og tidligere versioner af Windows styrer tjenesten RPC Locator (Remote Procedure Call) tjenestedatabasen med RPC-navne. I Windows Vista og senere versioner af Windows har denne tjeneste ikke nogen funktion og er kun medtaget af hensyn til programkompatibilitet.		Manuelt	Netværkstjeneste
Sekundært logon	Aktiverer startprocesser med alternative legitimationsoplysninger. Hvis denne tjeneste stoppes, vil denne type logon-adgang ikke være tilgængelig. Hvis denne tjeneste er deaktiveret, vil tjenester, der er direkte afhængige af den, ikke kunne startes.		Manuelt	Lokalt system
SENS (System Event Notification Service)	Overvåger systemhændelser og giver abonnenter besked om COM+-hændelsessystemet for disse hændelser.	Kører	Automatisk	Lokalt system
Sensordatatjeneste	Leverer data fra en række sensorer		Manuel (udløser start)	Lokalt system
Sensorovervågningstjeneste	Overvåger forskellige sensorer for at afsløre data og tilpasse dem systemet og brugertilstanden. Hvis denne tjeneste stoppes eller deaktiveres, vil skærmens lysstyrke ikke blive tilpasset lysforholdene. Stop af denne tjeneste kan påvirke anden systemfunktionalitet og enkeltfunktioner.		Manuel (udløser start)	Lokal tjeneste
Sensortjeneste	En tjeneste til sensorer, der administrerer forskellige sensorers funktionalitet. Administrerer SDO (Simple Device Orientation) og historik for sensorer. Indlæser den SDO-sensor, der rapporterer ændringer i en enheds retning. Hvis tjenesten stoppes eller deaktiveres, bliver SDO-sensoren ikke indlæst, og der foretages ikke automatisk rotation. Indsamling af historik fra sensorer bliver også stoppet.		Manuel (udløser start)	Lokalt system
Server	Understøtter deling af filer, udskrifter og navngivne pipes på netværket for denne computer. Hvis denne tjeneste stoppes, vil disse funktioner ikke være tilgængelige. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.	Kører	Automatisk (udløser start)	Lokalt system
Server til Windows-kamerabillede	Giver flere klienter mulighed for at få adgang til videobilleder fra kameraenheder.		Manuel (udløser start)	Lokalt system
Shared PC Account Manager	Manages profiles and accounts on a SharedPC configured device		Deaktiveret	Lokalt system
Sikkerhedscenter	Tjenesten WSCSVC (Windows Sikkerhedscenter) overvåger og rapporterer om computerens sikkerhedstilstand, herunder firewall (til/fra), antivirus (til/fra/ikke opdateret), antispyware (til/fra/ikke opdateret), Windows Update (automatisk/manuel hentning og installation af opdateringer), Kontrol af brugerkonti (til/fra) og Internetindstillinger (anbefales/anbefales ikke). Tjenesten leverer COM-API'er, som uafhængige softwareleverandører kan bruge til at registrere tilstanden for deres produkter i Sikkerhedscenter. Brugergrænsefladen i Sikkerhed og vedligeholdelse bruger tjenesten til at levere beskeder på proceslinjen samt en grafisk visning af sikkerhedstilstanden i kontrolpanelet i Sikkerhed og vedligeholdelse. NAP (Network Access Protection) bruger tjenesten til at rapportere om klienternes sikkerhedstilstand til NAP-netværkspolitikserveren, så der kan træffes beslutninger om eventuel netværkskarantæne. Tjenesten har desuden et offentligt API, der gør det muligt for eksterne brugere at h	Kører	Automatisk (forsinket start)	Lokal tjeneste
Sikkerhedskontohåndtering	Når denne tjeneste starter, signalerer det til andre tjenester, at Sikkerhedskontohåndtering er klar til at acceptere forespørgsler. Deaktivering af denne tjeneste forhindrer andre tjenester i systemet i at blive underrettet, når Sikkerhedskontohåndtering er klar, hvilket igen kan forhindre disse tjenester i at starte korrekt. Denne tjeneste skal ikke deaktiveres.	Kører	Automatisk	Lokalt system
Slutpunktsgenerator i Windows Audio	Styrer lydenheder for tjenesten Windows Audio. Hvis denne tjeneste stoppes, fungerer lydenheder og -effekter ikke korrekt. Hvis denne tjeneste deaktiveres, kan enheder, der direkte afhænger af den, ikke starte	Kører	Automatisk	Lokalt system
Sms-routertjeneste til Microsoft Windows.	Distribuerer beskeder ud fra regler til de relevante klienter.		Manuel (udløser start)	Lokal tjeneste
SNMP Trap	Modtager trap-meddelelser, der er oprettet af lokale eller fjern-SNMP-agenter og videresender meddelelserne til SNMP-styringsprogrammer, der kører på denne computer. Hvis denne tjeneste er stoppet, modtager SNMP-baserede programmer på denne computer ikke SNMP-trap-meddelelser. Hvis denne tjeneste er deaktiveret, kan tjenester, der er direkte afhængige af den, ikke starte.		Manuelt	Lokal tjeneste
Softwarebeskyttelse	Aktiverer overførsel, installation og anvendelse af digitale licenser til Windows og Windows-programmer. Hvis denne tjeneste er deaktiveret, vil operativsystemet og programmer i licens muligvis køre i beskedtilstand. Det anbefales på det kraftigste, at du ikke deaktiverer tjenesten til softwarebeskyttelse.		Automatisk (forsinket start, udløser start)	Netværkstjeneste
Spatial Data-tjeneste	Denne tjeneste bruges til scenarier med opfattelse af afstande		Manuelt	Lokal tjeneste
SSDP-registrering	Finder enheder og tjenester på netværket, der anvender SSDP-registreringsprotokollen, f.eks. UPnP-enheder. Giver også meddelelse om SSDP-enheder og -tjenester, der kører på den lokale computer. Hvis meddelelsen stoppes, opdages SSDP-baserede enheder ikke. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.		Manuelt	Lokal tjeneste
SSTP-tjeneste (Secure Socket Tunneling Protocol)	Understøtter SSTP (Secure Socket Tunneling Protocol), der bruges til at oprette forbindelse til fjerncomputere via VPN. Hvis denne tjeneste er deaktiveret, kan brugerne ikke anvende SSTP til at få adgang til fjernservere.		Manuelt	Lokal tjeneste
Startprogram til DCOM Serverproces	Tjenesten DCOMLAUNCH starter COM- og DCOM-servere på baggrund af anmodninger om objektaktivering. Hvis tjenesten er stoppet eller deaktiveret, virker de programmer, der bruger COM eller DCOM, ikke korrekt. Det anbefales på det kraftigste, at tjenesten DCOMLAUNCH kører.	Kører	Automatisk	Lokalt system
Steam Client Service	Steam Client Service monitors and updates Steam content		Manuelt	Lokalt system
Strøm	Administrerer strømpolitikken og levering af meddelelser om strømpolitik.	Kører	Automatisk	Lokalt system
Styring af betalinger og NFC/SE	Administrerer betalinger og Near Field Communication-baserede (NFC) sikre elementer.		Manuel (udløser start)	Lokal tjeneste
Styring af enhedsinstallation	Giver mulighed for at registrere, hente og installere enhedsrelateret software. Hvis denne tjeneste er aktiveret, kan enheder være konfigureret med forældet software, så de måske ikke virker korrekt.		Manuel (udløser start)	Lokalt system
Styring af legitimationsoplysninger	Sørger for sikker lagring og hentning af legitimationsoplysninger til brugere, programmer og løsninger med sikkerhedstjenester.	Kører	Manuelt	Lokalt system
Synkroniseringsvært_42ad2	Denne tjeneste synkroniserer mail, kontakter, kalender og forskellige andre brugerdata. Mail og andre programmer, der er afhængige af denne funktionalitet, vil ikke fungere korrekt, når tjenesten ikke kører.	Kører	Automatisk (forsinket start)	Lokalt system
SysMain	Vedligeholder og forbedrer systemets ydeevne på længere sigt.		Deaktiveret	Lokalt system
System Guard Runtime Monitor Broker	Overvåger og bekræfter Windows-platformens integritet.	Kører	Automatisk (forsinket start, udløser start)	Lokalt system
Systemhændelsesmægler	Koordinerer udførelsen af baggrundsarbejde for WinRT-programmet. Hvis denne tjeneste stoppes eller deaktiveres, udløses baggrundsarbejde muligvis ikke.	Kører	Automatisk (udløser start)	Lokalt system
Systemtjeneste til Windows Push-meddelelser	Denne tjeneste kører i session 0 og er vært for meddelelsesplatformen og den forbindelsesprovider, som styrer forbindelsen mellem enheden og WNS-serveren.	Kører	Automatisk	Lokalt system
Telefontjeneste	Administrerer telefonitilstanden på enheden		Deaktiveret	Lokal tjeneste
Telekommunikation	Leverer TAPI-support til programmer, der styrer telefonenheder på den lokale computer og, via LAN-netværket, på servere, der også kører tjenesten.		Deaktiveret	Netværkstjeneste
Temaer	Indeholder administration af temaer på brugergrænsefladen.	Kører	Automatisk	Lokalt system
Tidsmægler	Koordinerer udførelsen af baggrundsarbejde for WinRT-programmet. Hvis denne tjeneste stoppes eller deaktiveres, udløses baggrundsarbejde muligvis ikke.	Kører	Manuel (udløser start)	Lokal tjeneste
Tilsluttede brugeroplevelser og telemetri	Tjenesten Tilsluttet brugeroplevelse og telemetri muliggør funktioner, der understøtter brug i programmet og tilsluttede brugeroplevelser. Derudover administrerer denne tjeneste hændelsesdreven indsamling og afsendelse af diagnosticerings- og brugsoplysninger (bruges til at forbedre oplevelsen og kvaliteten af Windows-platformen), når indstillingerne for diagnosticering og beskyttelse af personlige oplysninger om brug er aktiveret under Feedback og diagnosticering.		Deaktiveret	Lokalt system
Tjeneste for brugerstyret inputenhed (HID)	Aktiverer og vedligeholder brug af foruddefinerede genvejstaster på tastaturer, fjernbetjeninger og andre multimedieenheder. Du anbefales at holde denne tjeneste kørende.	Kører	Manuel (udløser start)	Lokalt system
Tjeneste til datadeling	Sikrer overførsel af data mellem programmer.	Kører	Manuel (udløser start)	Lokalt system
Tjeneste til optælling af chipkortenheder	Opretter softwareenhedsnoder for alle chipkortlæsere, der er tilgængelige i de enkelte sessioner. Hvis denne tjeneste er deaktiveret, kan WinRT-API'er ikke optælle chipkortlæsere.		Manuel (udløser start)	Lokalt system
Tjeneste til routing af WAP-pushmeddelelser (Wireless Application Protocol) fra Enhedshåndtering	Sender WAP-pushmeddelelser (Wireless Application Protocol), der modtages af enheden, og synkroniserer Enhedshåndtering-sessioner		Automatisk (forsinket start, udløser start)	Lokalt system
Tjeneste til sikkerhedskopiering på blokniveau	WBENGINE-tjenesten bruges af Windows Sikkerhedskopiering til at udføre sikkerhedskopiering og genoprettelse. Hvis denne tjeneste standses af en bruger, kan det medføre, at den sikkerhedskopiering eller genoprettelse, der kører i øjeblikket, ikke lykkes. Hvis du deaktiverer denne tjeneste, deaktiveres den sikkerhedskopiering og genoprettelse, der kører ved hjælp af Windows Sikkerhedskopiering, måske på denne computer.		Manuelt	Lokalt system
Tjeneste til skærmforbedring	En tjeneste til håndtering af skærmforbedring, f.eks. justering af lysstyrke.	Kører	Manuel (udløser start)	Lokalt system
Tjeneste til styring af virksomhedsapps	Aktivérer styring af virksomhedsapps.		Manuelt	Lokalt system
Tjeneste til tilmelding i Enhedshåndtering	Udfører aktiviteter til tilmelding af enheden i Enhedshåndtering		Manuelt	Lokalt system
Tjeneste til tilstandslager	Giver den nødvendige understøttelse af infrastrukturen for programmodellen.	Kører	Manuelt	Lokalt system
Tjenesten AssignedAccessManager	AssignedAccessManager-tjenesten understøtter kiosk-oplevelse i Windows.		Manuel (udløser start)	Lokalt system
Tjenesten Assistent til lokal profil	Denne tjeneste tilbyder profilstyring til abonnent-id-moduler		Manuel (udløser start)	Lokal tjeneste
Tjenesten BitLocker-drevkryptering	BDESVC er vært for tjenesten BitLocker-drevkryptering. BitLocker-drevkryptering giver sikker opstart af operativsystemet samt komplet drevkryptering for operativsystemet og faste eller flytbare diskenheder. Tjenesten tillader, at BitLocker beder brugeren om at foretage forskellige handlinger i forbindelse med diskenhederne, når de tilsluttes, og den låser automatisk diskenheder op uden brugermedvirken. Den gemmer desuden genoprettelsesoplysninger i Active Directory, og hvis det er nødvendigt, sikrer den, at de nyeste genoprettelsescertifikater bruges. Hvis du standser eller deaktiverer tjenesten, vil brugerne ikke kunne benytte denne funktion.		Deaktiveret	Lokalt system
Tjenesten Bluetooth-brugersupport_42ad2	Tjenesten til Bluetooth-brugersupport sikrer korrekt funktionalitet af Bluetooth-funktioner, der er relevante for hver brugersession.		Manuel (udløser start)	Lokalt system
Tjenesten Bluetooth-support	Bluetooth-tjenesten understøtter registrering og tilknytning af Bluetooth-fjernenheder. Hvis du standser eller deaktiverer denne tjeneste, kan Bluetooth-enheder, der allerede er installeret, måske ikke køre, og nye enheder kan måske ikke registreres eller tilknyttes.		Manuel (udløser start)	Lokal tjeneste
Tjenesten Brugerprofil	Denne tjeneste er ansvarlig for indlæsning og deaktivering af brugerprofiler. Hvis denne tjeneste afbrydes eller deaktiveres, kan brugerne ikke længere logge af og på, programmerne kan have svært ved at hente brugernes data, og komponenter, der er registreret til at modtage profilhændelsesmeddelelser, vil ikke modtage disse meddelelser.	Kører	Automatisk	Lokalt system
Tjenesten Demotilstand	Tjenesten Demotilstand styrer aktiviteterne på enheden, mens enheden er i demotilstand.		Deaktiveret	Lokalt system
Tjenesten Enhedstilknytning	Gør det muligt at oprette pardannelse mellem systemet og kabelbaserede eller trådløse enheder.	Kører	Manuel (udløser start)	Lokalt system
Tjenesten Filhistorik	Beskytter brugerfiler mod utilsigtet sletning eller beskadigelse ved at kopiere dem til en sikkerhedskopiplacering		Manuel (udløser start)	Lokalt system
Tjenesten Grænseflade til netværkslagring	Denne tjeneste leverer netværksmeddelelser, f.eks. tilføjelse/sletning af grænseflade, til klienter i brugertilstand. Hvis du standser denne tjeneste, afbrydes forbindelsen til netværket. Hvis denne tjeneste deaktiveres, kan alle de tjenester, der direkte afhænger af den, ikke startes.	Kører	Automatisk	Lokal tjeneste
Tjenesten HV Host	Indeholder en grænseflade for Hyper-V-hypervisoren, der leverer ydelsestællere for hver partition til værtsoperativsystemet.		Manuel (udløser start)	Lokalt system
Tjenesten Hyper-V Impuls	Overvåger tilstanden af den virtuelle maskine ved at rapportere en impuls med jævne intervaller. Denne tjeneste hjælper dig med at identificere kørende virtuelle maskiner, der ikke længere svarer.		Deaktiveret	Lokalt system
Tjenesten Microsoft Defender Antivirus	Er med til at beskytte brugere mod skadelig software og andre former for potentielt uønsket software		Manuelt	Lokalt system
Tjenesten Microsoft Defender Antivirus Network Inspection	Er med til at beskytte mod forsøg på indtrængen, der er målrettet mod kendte og nyopdagede sikkerhedsrisici i netværksprotokoller		Manuelt	Lokal tjeneste
Tjenesten Netværksinstallation	Tjenesten Netværksinstallation administrerer installationen af netværksdrivere og giver mulighed for konfiguration af netværksindstillinger på lavt niveau. Hvis denne tjeneste stoppes, kan alle igangværende driverinstallationer blive annulleret.		Manuel (udløser start)	Lokalt system
Tjenesten Netværksliste	Identificerer de netværk, computeren har oprettet forbindelse til, indsamler og gemmer egenskaber for disse netværk og underretter programmer, når disse egenskaber ændres.	Kører	Manuelt	Lokal tjeneste
Tjenesten Sprogoplevelse	Giver infrastrukturunderstøttelse til installation og konfiguration af lokaliserede Windows-ressourcer. Denne tjeneste startes efter behov, og hvis den er deaktiveret, vil yderligere Windows-sprog ikke blive installeret på systemet, og Windows fungerer muligvis ikke korrekt.		Manuelt	Lokalt system
Tjenesten TCP/IP NetBIOS Helper	Giver support til tjenesten NetBIOS over TCP/IP (NetBT) og NetBIOS-navnefortolkning til klienter på netværket og gør det muligt for brugere at dele filer, udskrive og logge på netværket. Hvis denne tjeneste er stoppet, er disse funktioner muligvis ikke tilgængelige. Hvis denne tjeneste deaktiveres, kan alle de tjenester, der direkte afhænger af den, ikke startes.	Kører	Manuel (udløser start)	Lokal tjeneste
Tjenesten til volumetrisk lydkomposition	Stiller spatialanalyse for lydsimulering til rådighed i mixed reality.		Manuelt	Lokal tjeneste
Tjenesten Touchtastatur og håndskriftspanel	Aktiverer håndskriftsfunktionalitet med Touchtastatur og håndskriftspanel	Kører	Manuel (udløser start)	Lokalt system
Tjenesten Windows Biometri	Tjenesten Windows Biometri giver klientprogrammer mulighed for at hente, sammenligne, ændre og gemme biometriske data uden direkte adgang til eventuel biometrisk hardware eller eksempler. Tjenesten hostes i en privilegeret SVCHOST-proces.		Manuel (udløser start)	Lokalt system
Tjenesten Windows Fejlrapportering	Giver mulighed for rapportering af fejl, når programmer ikke virker eller ikke svarer, og viser eksisterende løsningsforslag. Giver også mulighed for oprettelse af logfiler til diagnosticerings- og reparationstjenester. Hvis denne tjeneste afbrydes, fungerer fejlrapporteringen muligvis ikke korrekt, og der vises muligvis ikke resultater for diagnosticerings- og reparationstjenester.		Manuel (udløser start)	Lokalt system
Tjenesten Windows-administration	Udfører administration, herunder klargørings- og registreringsaktiviteter		Manuelt	Lokalt system
Tjenesten Windows-skrifttypecache	Optimerer ydeevnen i programmer ved at cachelagre de mest anvendte skrifttypedata. Programmer starter tjenesten, hvis den ikke allerede kører. Den kan deaktiveres, men det vil medføre en dårligere ydeevne for programmerne.	Kører	Automatisk	Lokal tjeneste
Udbydervært til registrering af funktioner	Tjenesten FDPHOST er vært for udbydere af funktionsregistrering for netværksregistrering. Disse udbydere af funktionsregistrering leverer netværksregistreringstjenester for SSDP (Simple Services Discovery Protocol) og WS-D-protokollen Web Services – Discovery . Hvis du standser eller deaktiverer FDPHOST-tjenesten, deaktiveres netværksregistrering for disse protokoller, når der bruges funktionsregistrering. Når denne tjeneste ikke er tilgængelig, kan netværkstjenester, der bruger funktionsregistrering, og som er afhængige af disse registreringsprotokoller, ikke finde netværksenheder eller ressourcer.		Manuelt	Lokal tjeneste
Udgivelse af funktionsregistreringsressourcer	Udgiver denne computer og de ressourcer, der er knyttet til computeren, så de kan findes via netværket. Hvis denne tjeneste stoppes, udgives netværksressourcerne ikke længere, og de kan ikke findes af andre computere på netværket.		Manuel (udløser start)	Lokal tjeneste
Udk-brugertjeneste_42ad2	Tjeneste til shell-komponenter		Manuelt	Lokalt system
Understøttelse af kontrolpanelet Problemrapporter	Denne tjeneste understøtter visning, afsendelse og sletning af problemrapporter på systemniveau for kontrolpanelet Problemrapporter.		Manuelt	Lokalt system
User Experience Virtualization Service	Provides support for application and OS settings roaming		Deaktiveret	Lokalt system
Virtuel disk	Giver tjenester til håndtering af diske, diskenheder, filsystemer og lagringsmatrixer.		Manuelt	Lokalt system
Vis politiktjeneste	Administrerer forbindelsen og konfigurationen af lokale og eksterne skærme	Kører	Automatisk (forsinket start)	Lokal tjeneste
Vært for UPnP-enheder	Tillader, at UPnP-enheder bruger denne computer som vært. Hvis tjenesten stoppes, kan UPnP-enheder på computeren ikke fungere, og der kan ikke tilføjes flere enheder, som bruger computeren som vært. Hvis tjenesten deaktiveres, kan tjenester, der direkte er afhængige af den, ikke startes.		Manuelt	Lokal tjeneste
Værtstjeneste for Windows-krypteringsprovider	Værtstjeneste for Windows-krypteringsprovider, også kaldet WEP, er mæglerkryptering med relaterede funktionaliteter fra tredjeparts krypteringsprovidere til processer, der skal evaluere og anvende EAS-politikker. Hvis den stoppes, kompromitteres EAS-overholdelseskontrol, der er etableret af de forbundne mailkonti		Manuel (udløser start)	Lokal tjeneste
WalletService	Værtsobjekter, der bruges af klienter til tegnebogen		Manuelt	Lokalt system
WarpJITSvc	Provides a JIT out of process service for WARP when running with ACG enabled.		Manuel (udløser start)	Lokal tjeneste
Webklient	Gør det muligt for Windows-baserede programmer at oprette, få adgang til og ændre internetbaserede filer. Hvis denne tjeneste stoppes, er disse funktioner ikke tilgængelige. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.		Manuel (udløser start)	Lokal tjeneste
Webkontoadministrator	Webkontoadministratoren bruger denne tjeneste til at give mulighed for enkeltogon til apps og tjenester.	Kører	Manuelt	Lokalt system
Wi-Fi Direct-tjenester - Forbindelsesstyring	Administrerer forbindelser til trådløse tjenester, herunder trådløs skærm og docking.		Manuel (udløser start)	Lokal tjeneste
Windows Audio	Styrer lyden i Windows-baserede programmer. Hvis denne tjeneste stoppes, fungerer lydenheder og -effekter ikke korrekt. Hvis denne tjeneste deaktiveres, kan enheder, der direkte afhænger af den, ikke startes.	Kører	Automatisk	Lokal tjeneste
Windows Connect Now - Config Registrar	WCNCSVC er vært for Windows Connect Now Configuration, som er Microsofts implementering af WPS-protokollen (Wi-Fi Protected Setup). Det bruges til at konfigurere indstillinger for trådløse LAN-netværk for et adgangspunkt eller en trådløs enhed. Tjenesten startes via programmering efter behov.		Manuelt	Lokal tjeneste
Windows Defender Advanced Threat Protection-tjeneste	Tjenesten Windows Defender Advanced Threat Protection hjælper med at beskytte dig mod avancerede trusler ved at overvåge og rapportere sikkerhedshændelser, der finder sted på computeren.		Manuelt	Lokalt system
Windows Defender Firewall	Med Windows Defender Firewall kan du beskytte computeren ved at forhindre uautoriserede brugere i at få adgang til computeren via internettet eller et netværk.	Kører	Automatisk	Lokal tjeneste
Windows Event Collector	Denne tjeneste håndterer vedvarende abonnementer på handlinger fra fjernkilder, der understøtter WS-Management-protokollen. Det inkluderer Windows Vista-hændelseslogfiler, hardware og IPMI-aktiverede hændelseskilder. Tjenesten gemmer videresendte hændelser i en lokal hændelseslogfil. Hvis denne tjeneste standses eller deaktiveres, kan hændelsesabonnementer ikke oprettes, og videresendte hændelser kan ikke accepteres.		Manuelt	Netværkstjeneste
Windows Forbindelsesstyring	Træffer automatiske beslutninger om at oprette/afbryde forbindelse på basis af de netværksforbindelsesindstillinger, der er tilgængelige for pc'en, og gør det muligt at styre netværksforbindelsen på basis af indstillingerne for gruppepolitikken.	Kører	Automatisk (udløser start)	Lokal tjeneste
Windows Insider-tjeneste	Leverer understøttelse af infrastruktur til Windows Insider Program. Denne tjeneste skal være aktiveret, for at Windows Insider Program kan fungere.		Deaktiveret	Lokalt system
Windows Installer	Tilføjer, ændrer og fjerner programmer, der er angivet som en Windows Installer-pakke (*.msi, *.msp). Hvis tjenesten deaktiveres, kan alle tjenester, der er direkte afhængige af denne tjeneste, ikke starte.		Manuelt	Lokalt system
Windows Management Instrumentation	Omfatter en fælles grænseflade og objektmodel, der giver adgang til oplysninger om administration af operativsystemer, enheder, programmer og tjenester. Hvis denne tjeneste stoppes, vil de fleste Windows-baserede programmer ikke fungere korrekt. Hvis denne tjeneste deaktiveres, vil alle tjenester, som er direkte afhængige af den, ikke kunne starte.	Kører	Automatisk	Lokalt system
Windows Mixed Reality OpenXR Service	Enables Mixed Reality OpenXR runtime functionality		Manuelt	Lokalt system
Windows Perception Service	Giver mulighed for rumlig opfattelse, rumligt input og holografisk gengivelse.		Manuel (udløser start)	Lokal tjeneste
Windows Perception Simulation Service	Muliggør simulering af rumlig opfattelse, styring af virtuelt kamera og simulering af rumlige input.		Manuelt	Lokalt system
Windows Presentation Foundation Font Cache 3.0.0.0	Optimerer ydeevnen for WPF-programmer (Windows Presentation Foundation) ved at cachelagre almindeligt brugte skriftdata. WPF-programmer starter denne tjeneste, hvis den ikke allerede kører. Den kan deaktiveres, men det vil forringe ydeevnen for WPF-programmer.	Kører	Manuelt	Lokal tjeneste
Windows Push-beskedbrugertjenester_42ad2	Denne tjeneste er vært for platformen Windows-meddelelser, som giver understøttelse af lokale meddelelser og pushmeddelelser. De understøttede meddelelser er felt, toast og rå.	Kører	Automatisk	Lokalt system
Windows PushToInstall-tjeneste	Giver infrastrukturunderstøttelse til Microsoft Store. Denne tjeneste startes automatisk, og hvis den er deaktiveret, vil fjerninstallationer ikke fungere korrekt.		Manuel (udløser start)	Lokalt system
Windows Remote Management (WS-Management)	Windows Remote Management-tjenesten (WinRM) implementerer protokollen WS-Management til fjernadministration. WS-Management er en standardwebtjenesteprotokol til fjernadministration af software og hardware. WinRM-tjenesten lytter efter anmodninger om WS-Management på netværket og behandler dem. WinRM-tjenesten skal konfigureres med en lytter vha. kommandolinjeværktøjet winrm.cmd eller via gruppepolitikken for at kunne lytte over netværket. WinRM-tjenesten giver adgang til WMI-data og mulighed for indsamling af hændelser. Indsamling af hændelser og abonnement på hændelser kræver, at tjenesten kører. WinRM-meddelelser bruger HTTP og HTTPS til transport. WinRM-tjenesten er ikke afhængig af IIS, men er forudkonfigureret til at dele en port med IIS på den samme computer. WinRM-tjenesten reserverer URL-præfikset /wsman. For at forhindre, at der opstår konflikt med IIS, skal administratorer sikre, at alle websteder, som hostes på IIS, ikke bruger URL-præfikset /wsman.		Manuelt	Netværkstjeneste
Windows Search	Giver indeksering af indhold, cachelagring af egenskaber og søgeresultater for filer, mail og andet indhold.		Deaktiveret	Lokalt system
Windows Sikkerhedskopiering	Har funktioner til Sikkerhedskopiering og gendannelse.	Kører	Manuelt	Lokalt system
Windows Sikkerhed-tjenesten	Windows Sikkerhed-tjenesten håndterer samlet enhedsbeskyttelse og tilstandsoplysninger	Kører	Manuelt	Lokalt system
Windows Time	Maintains date and time synchronization on all clients and servers in the network. If this service is stopped, date and time synchronization will be unavailable. If this service is disabled, any services that explicitly depend on it will fail to start.		Manuel (udløser start)	Lokal tjeneste
Windows Update	Aktiverer godkendelse, hentning og installation af opdateringer til Windows og andre programmer. Hvis denne tjeneste er deaktiveret, kan brugere af denne computer ikke bruge Windows Update eller dets automatiske opdateringsfunktion, og programmer vil ikke kunne bruge Windows Update Agent (WUA) API.	Kører	Manuel (udløser start)	Lokalt system
Windows Update Medic Service	Aktiverer afhjælpning og beskyttelse af Windows Update-komponenter.		Manuelt	Lokalt system
Windows-billedscanning	Stiller billedscanningstjenester til rådighed for scannere og kameraer		Deaktiveret	Lokal tjeneste
Windows-hændelseslog	Denne tjeneste styrer hændelser og hændelseslogfiler. Den understøtter logføringshændelser, forespørgselshændelser, oprettelse af abonnement på hændelser, arkivering af hændelseslogfiler og styring af hændelsesmetadata. Den kan vise hændelser i både XML og almindeligt tekstformat. Hvis tjenesten standses, kan det svække systemets sikkerhed og pålidelighed.	Kører	Automatisk	Lokal tjeneste
Windows-tjenesten Licensstyring	Giver infrastrukturunderstøttelse til Microsoft Store. Denne tjeneste startes efter behov, og hvis den er deaktiveret, vil indhold, der er købt via Microsoft Store, ikke fungere korrekt.	Kører	Manuel (udløser start)	Lokal tjeneste
WinHTTP-tjenesten Web Proxy Auto-Discovery	WinHTTP implementerer klient-HTTP-stakken og tilbyder udviklere en Win32 API- og COM-automatiseringskomponent til afsendelse og HTTP-anmodninger og modtagelse af svar. Derudover understøtter WinHTTP automatisk registrering af en proxykonfiguration via implementeringen af WPAD-protokollen (Web Proxy Auto-Discovery).	Kører	Manuelt	Lokal tjeneste
WLAN AutoConfig	WLANSVC-tjenesten indeholder den logik, der skal bruges til at konfigurere, registrere, oprette forbindelse til og afbryde forbindelsen fra et trådløst lokalnetværk (WLAN) som defineret i IEEE 802.11-standarderne. Den indeholder også den logik, der skal bruges til at vende computeren mod et softwareadgangspunkt, så andre enheder eller computere kan oprette trådløs forbindelse til din computer ved hjælp af et WLAN-kort, der understøtter denne funktion. Hvis du standser eller deaktiverer WLANSVC-tjenesten, bliver alle WLAN-kort på din computer utilgængelige fra grænsefladen for Windows-netværk. Det anbefales på det kraftigste, at WLANSVC-tjenesten kører, hvis du har et WLAN-kort.	Kører	Automatisk	Lokalt system
WMI-ydelseskort	Angiver oplysninger om ydelses-DLL-filen fra WMI-providere (Windows Management Instrumentation) til klienter på netværket. Denne tjeneste kører kun, når Hjælpe-DLL til ydelsesdata er aktiveret.		Manuelt	Lokalt system
WWAN AutoConfig	Denne tjeneste administrerer datakort eller integrerede modulkort for mobile bredbånd (GSM & CDMA) og forbindelser ved at konfigurere netværket automatisk. Det anbefales på det kraftigste, at denne tjeneste bliver ved med at køre for at opnå den bedste brugeroplevelse i forbindelse med mobile bredbåndsenheder.		Manuelt	Lokalt system
Xbox Accessory Management Service	This service manages connected Xbox Accessories.		Deaktiveret	Lokalt system
Xbox Live Auth Manager	Giver dig godkendelses- og adgangstjenester til Xbox Live. Hvis denne tjeneste stoppes, vil nogle programmer muligvis ikke virke korrekt.		Deaktiveret	Lokalt system
Xbox Live Spillagring	Denne tjeneste synkroniserer gemte data fra spil, der har lagring af Xbox Live spil slået til. Hvis denne tjeneste afbrydes, vil gemte data fra spil ikke blive uploadet til eller downloadet fra Xbox Live.		Deaktiveret	Lokalt system
Xbox Live-netværkstjeneste	Denne tjeneste understøtter programmeringsinterfacet Windows.Networking.XboxLive.		Deaktiveret	Lokalt system
Ydelseslogger og -beskeder	Performance Logs and Alerts Indsamler ydelsesdata fra lokale computere eller fjerncomputere baseret på forudkonfigurerede planlægningsparametre og skriver derefter dataene til en logfil eller udløser en besked. Hvis denne tjeneste stoppes, indsamles der ikke ydelsesoplysninger. Hvis denne tjeneste deaktiveres, vil alle tjenester, som er direkte afhængige af den, ikke starte.	Kører	Automatisk	Lokal tjeneste
Øjebliksbillede af diskenhed	Administrerer og implementerer øjebliksbilleder, der bruges til sikkerhedskopiering og andre formål. Hvis denne tjeneste stoppes vil øjebliksbilleder ikke være tilgængelige til sikkerhedskopiering, og sikkerhedskopieringen mislykkes muligvis. Hvis denne tjeneste deaktiveres, kan tjenester, der er direkte afhængige af den, ikke starte.		Manuelt	Lokalt system
